### ISSUE TITLE
app-header: Please add support for <img> element

### ISSUE THREAD

**Issue by JosefJezek** [PolymerElements/app-layout#225]
Could you add support for `img` element to `app-header`? I need `load` callback for css transition effect...

Like as in `app-box` element...

```html
<div id="backgroundFrontLayer">
  <content select="[backgroundFrontLayer]"></content>
</div>
```

```html
<app-header>
  <img backgroundFrontLayer src="/images/bg.jpg" on-load="_onHeaderBackgroundLoad" on-error="_onHeaderBackgroundError">
</app-header>
```

**Comment by blasten** [comment]
@JosefJezek you could create the image programmatically (it doesn't need to be attached to the DOM)  and finally run the transition once the `load` callback fired. The second request should come from the cache if the headers were sent appropriately.

**Comment by JosefJezek** [comment]
How to programmatically insert image to `<div id="backgroundFrontLayer">` in `app-header`? Please snippet...

**Comment by blasten** [comment]
you don't need to insert the image in the DOM, e.g:

 ```css
app-header {
  --app-header-background-front-layer: {
    background-image: url(src);
    transition: opacity 0.2s;
    opacity: 0;
  };
}

app-header.loaded {
  --app-header-background-front-layer: {
    opacity: 1;
  };
}
```

and then 
```js
// when load fired
appHeader.classList.add('loaded');
appHeader.updateStyles();
```

**Comment by JosefJezek** [comment]
`app-header` hasn't `onload` callback. I need ASAP transition effect after loaded image for home page.

http://stackoverflow.com/questions/24335369/component-onload-not-fired-anymore

**Comment by JosefJezek** [comment]
Why css `background-image` is better then `img` element? I can also  style `img` elament...

```css
img {
        object-fit: cover;
        width: 100%;
        height: 100%;
      }
```
