### ISSUE TITLE
Suggestion to add mixin --app-header-content-container for app-header

### ISSUE THREAD

**Issue by motss** [PolymerElements/app-layout#284]
This is to propose a mixin for `app-header` to style the underlying `#contentContainer` just like `app-drawer`.

```css
  #contentContainer {
    position: relative;
    width: 100%;
    height: 100%;

    @apply(--app-header-content-container);
  }
```

WDYT?
