### ISSUE TITLE
--app-grid-expandible-item fails when --app-grid-gutter is 0

### ISSUE THREAD

**Issue by bennyp123** [PolymerElements/app-layout#380]
### Description

when `--app-grid-gutter` is 0, `--app-grid-expandible-item` applies invalid rules such as:

```css
/* specified mixins */
      :host {
        --app-grid-columns: 6;
        --app-grid-expandible-item-columns: 2;
        --app-grid-item-height: auto;
        --app-grid-gutter: 1px;
      }
```

```css
/* rendered rule */
    flex-basis: calc((100% - 0.1px) / 6 * 2 - 0) !important;
    max-width: calc((100% - 0.1px) / 6 * 2 - 0) !important;
```
### Expected outcome
app-grid-expandible-item should be applied as normal

### Actual outcome
app-grid-expandible-item is not applied, as css rules are invalid

### Live Demo

https://jsbin.com/nekewomixa/edit?html,output
### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10
